SDC and Gateway are notified of changed mdm_ips.  Termination race fix. Workaround for SDC termination

diff --git a/trusty/scaleio-mdm/hooks/common b/trusty/scaleio-mdm/hooks/common
--- a/trusty/scaleio-mdm/hooks/common
+++ b/trusty/scaleio-mdm/hooks/common
@@ -22,12 +22,12 @@ function server-cmd {
 	set +e
 	FACTER_mdm_ips=$MY_MDMS puppet apply -e "$1" --detailed-exitcodes
 	local exit_code=$?
-  if [[ $exit_code == 0 || $exit_code == 2 ]]; then
-    juju-log "The run succeeded. Exit code is $exit_code."
-  else
-    juju-log "The run failed. Exit code is $exit_code."
-    exit 1
-  fi
+	if [[ $exit_code == 0 || $exit_code == 2 ]]; then
+		juju-log "The run succeeded. Exit code is $exit_code."
+	else
+		juju-log "The run failed. Exit code is $exit_code."
+		exit 1
+	fi
 	set -e
 }
 
@@ -39,6 +39,22 @@ function log-relation {
 	rel_name=${convert-name $JUJU_REMOTE_UNIT}
 	rel_ip=`relation-get private-address`
 	juju-log "$1: my name is $MY_NAME, relation is $rel_name, $rel_ip"
+}
+
+function relation-set-all {
+	leader=`is-leader`
+	if [ $leader != 'True' ]; then exit; fi
+
+	mdm_ips=`leader-get mdm_ips`
+	mdm_ips=${mdm_ips%,}
+
+	rids=`relation-ids scaleio-mdm`
+	if [ -n "$rids" ]; then
+		juju-log "ScaleIO MDM notifies SDCs and Gateways about changes: $rids"
+		for rid in $( echo $rids ); do
+			relation-set -r $rid mdm_ips=$mdm_ips
+	    done
+	fi
 }
 
 function size-of {
@@ -116,6 +132,8 @@ function resize-cluster {
 
 		leader-set resize_cluster=False cluster_mode=$cluster_mode mdm_ips=$mdm_ips tbs=$tbs managers=$managers\
 			tbs_ready=$tbs_ready managers_ready=$managers_ready standby_ips=$standby_ips
+		
+		relation-set-all
 	fi
 
 	# Check and reduce the Cluster
@@ -147,5 +165,7 @@ function resize-cluster {
 
 		leader-set resize_cluster=False cluster_mode=$cluster_mode mdm_ips=$mdm_ips tbs=$tbs managers=$managers\
 			tbs_ready=$tbs_ready managers_ready=$managers_ready standby_ips=$standby_ips
+		
+		relation-set-all
 	fi
 }
diff --git a/trusty/scaleio-mdm/hooks/scaleio-mdm-relation-departed b/trusty/scaleio-mdm/hooks/scaleio-mdm-relation-departed
--- a/trusty/scaleio-mdm/hooks/scaleio-mdm-relation-departed
+++ b/trusty/scaleio-mdm/hooks/scaleio-mdm-relation-departed
@@ -2,6 +2,8 @@
 my_dir="$(dirname "$0")"
 . "$my_dir/common"
 
+status=`status-get`
+if [ $status == 'terminated']; then exit; fi
 leader=`is-leader`
 if [ $leader != 'True' ]; then exit; fi
 
@@ -11,10 +13,17 @@ remote_ip=`relation-get private-address`
 if [[ $remote_name == "scaleio_sdc"* ]]; then
 	log-relation "ScaleIO SDC $remote_name departing"
 	
-	cluster-cmd "scaleio::sdc { 'sdc $remote_name': ip=>'$remote_ip', ensure=>'absent' }"
+	# TODO When scli --remove_sdc command is issued even with --i_am_sure, if SDC is still connected,
+	# the command fails and unit will go to error state. Most probably a bug in ScaleIO.
+	# That's why the following command cannot be employed
+	# cluster-cmd "scaleio::sdc { 'sdc $remote_name': ip=>'$remote_ip', ensure=>'absent' }"
+	# Workaround is used:
+	set +e
+	FACTER_mdm_ips=$MY_MDMS puppet apply -e "scaleio::login {'login': password=>$MY_PASSWORD} -> \
+		scaleio::sdc { 'sdc $remote_name': ip=>'$remote_ip', ensure=>'absent'}"
+	set -e
 
 	log-relation "ScaleIO SDS $remote_name departed"
 else
 	log-relation "ScaleIO GW departed"
 fi
-	
