3-node cluster works, simultaneous additions allowed

diff --git a/trusty/scaleio-mdm/hooks/common b/trusty/scaleio-mdm/hooks/common
--- a/trusty/scaleio-mdm/hooks/common
+++ b/trusty/scaleio-mdm/hooks/common
@@ -6,8 +6,13 @@ if [ $# -eq 1 ] && [ $1 == "-d" ] ; then
   . "$my_dir/debug"
 fi
 
+function convert-name {
+  echo ${1//[-\/]/_}
+}
+
 MY_IP=`unit-get private-address`
-MY_NAME=${JUJU_UNIT_NAME/\//-}
+MY_NAME=$(convert-name $JUJU_UNIT_NAME)
+echo $MY_NAME
 MY_PASSWORD=`config-get password`
 MY_MDMS=`leader-get mdm_ips`
 if [ -z "$MY_MDMS" ]; then MY_MDMS='127.0.0.1'; fi
@@ -17,11 +22,9 @@ function server-cmd {
   set +e
   FACTER_mdm_ips=$MY_MDMS puppet apply --modulepath="/home/alevine/shared:/etc/puppet/modules" -e "$1" --detailed-exitcodes
   local exit_code=$?
-  if [[ $exit_code == 0 || $exit_code == 2 ]]; then
-    juju-log "The run succeeded. Exit code is $exit_code."
-  else
-    juju-log "The run failed. Exit code is $exit_code."
-    exit 1
+  if [[ $exit_code != 0 && $exit_code != 2 ]]; then
+    juju-log "The run $1 failed. Exit code is $exit_code."
+    if [ -n "$2" ] && [ "$2" != "ignore_error" ]; then exit 1; fi
   fi
   set -e
 }
@@ -31,7 +34,7 @@ function cluster-cmd {
 }
 
 function log-relation {
-  remote_name=${JUJU_REMOTE_UNIT/\//-} 
-  remote_ip=`relation-get private-address`
-  juju-log "$1: $remote_name, $remote_ip"
+  rel_name=${convert-name $JUJU_REMOTE_UNIT}
+  rel_ip=`relation-get private-address`
+  juju-log "$1: my name is $MY_NAME, relation is $rel_name, $rel_ip"
 }
