fix setting high_performance for sdc and remove sdcs_ready array

diff --git a/trusty/scaleio-mdm/hooks/scaleio-mdm-relation-departed b/trusty/scaleio-mdm/hooks/scaleio-mdm-relation-departed
--- a/trusty/scaleio-mdm/hooks/scaleio-mdm-relation-departed
+++ b/trusty/scaleio-mdm/hooks/scaleio-mdm-relation-departed
@@ -3,34 +3,27 @@ my_dir="$(dirname "$0")"
 . "$my_dir/common"
 
 status=`status-get`
-if [ $status == 'terminated']; then exit; fi
+if [ $status == 'terminated' ]; then exit; fi
 leader=`is-leader`
 if [ $leader != 'True' ]; then exit; fi
 
 remote_name=$(convert-name $JUJU_REMOTE_UNIT)
 remote_ip=`relation-get private-address`
-sdcs_ready=`leader-get sdcs_ready`
 
 if [[ $remote_name == "scaleio_sdc"* ]]; then
-	log-relation "ScaleIO SDC $remote_name departing"
+  log-relation "ScaleIO SDC $remote_name departing"
 
-	if ! [ -z "${sdcs_ready-}" ]; then
-		to_remove="$remote_ip,"
-		sdcs_ready=${sdcs_ready/$to_remove}
-		leader-set sdcs_ready=$sdcs_ready
-	fi
+  # TODO When scli --remove_sdc command is issued even with --i_am_sure, if SDC is still connected,
+  # the command fails and unit will go to error state. Most probably a bug in ScaleIO.
+  # That's why the following command cannot be employed
+  # cluster-cmd "scaleio::sdc { 'sdc $remote_name': ip=>'$remote_ip', ensure=>'absent' }"
+  # Workaround is used:
+  set +e
+  FACTER_mdm_ips=$MY_MDMS puppet apply -e "scaleio::login {'login': password=>$MY_PASSWORD} -> \
+    scaleio::sdc { 'sdc $remote_name': ip=>'$remote_ip', ensure=>'absent'}"
+  set -e
 
-	# TODO When scli --remove_sdc command is issued even with --i_am_sure, if SDC is still connected,
-	# the command fails and unit will go to error state. Most probably a bug in ScaleIO.
-	# That's why the following command cannot be employed
-	# cluster-cmd "scaleio::sdc { 'sdc $remote_name': ip=>'$remote_ip', ensure=>'absent' }"
-	# Workaround is used:
-	set +e
-	FACTER_mdm_ips=$MY_MDMS puppet apply -e "scaleio::login {'login': password=>$MY_PASSWORD} -> \
-		scaleio::sdc { 'sdc $remote_name': ip=>'$remote_ip', ensure=>'absent'}"
-	set -e
-
-	log-relation "ScaleIO SDC $remote_name departed"
+  log-relation "ScaleIO SDC $remote_name departed"
 else
-	log-relation "ScaleIO GW departed"
+  log-relation "ScaleIO GW departed"
 fi
