SDC notifies Scaleio-Openstack that it's ready. Fixes for various removing services

diff --git a/trusty/scaleio-mdm/hooks/scaleio-sds-relation-departed b/trusty/scaleio-mdm/hooks/scaleio-sds-relation-departed
--- a/trusty/scaleio-mdm/hooks/scaleio-sds-relation-departed
+++ b/trusty/scaleio-mdm/hooks/scaleio-sds-relation-departed
@@ -2,14 +2,16 @@
 my_dir="$(dirname "$0")"
 . "$my_dir/common"
 
-status=`status-get`
-if [ $status == 'terminated']; then exit; fi
 leader=`is-leader`
 if [ $leader != 'True' ]; then exit; fi
 
 remote_name=$(convert-name $JUJU_REMOTE_UNIT)
 log-relation "ScaleIO SDS $remote_name departing"
 
-cluster-cmd "scaleio::sds { 'sds $remote_name': name=>'$remote_name', ensure=>'absent' }"
+# TODO: Workaround for non-working cluster when 3 goes to 1. During MDM service removal the following will fail	
+set +e
+FACTER_mdm_ips=$MY_MDMS puppet apply -e "scaleio::login {'login': password=>$MY_PASSWORD} -> \
+	scaleio::sds { 'sds $remote_name': name=>'$remote_name', ensure=>'absent' }"
+set -e
 
-log-relation "ScaleIO SDS $remote_name departed, $status"
+log-relation "ScaleIO SDS $remote_name departed"
