update error handling for puppet call in all charms

diff --git a/trusty/scaleio-sds/hooks/common b/trusty/scaleio-sds/hooks/common
--- a/trusty/scaleio-sds/hooks/common
+++ b/trusty/scaleio-sds/hooks/common
@@ -4,36 +4,46 @@ set -eu
 
 if [ $# -eq 1 ] && [ $1 == "-d" ]
 then
-	. "$my_dir/debug"
+  . "$my_dir/debug"
 fi
 
 MY_IP=`unit-get private-address`
-MY_NAME=${JUJU_UNIT_NAME/\//-} 
+MY_NAME=${JUJU_UNIT_NAME/\//-}
 MY_PASSWORD=`config-get password`
 
 function convert-name {
-	${$1/\//-}
+  ${$1/\//-}
 }
 
 function server-cmd {
-	puppet apply  --modulepath="/home/alevine/shared:/etc/puppet/modules"  -e "$1"
+  juju-log "Running server-cmd with '$1'"
+  set +e
+  puppet apply --modulepath="/home/alevine/shared:/etc/puppet/modules" -e "$1" --detailed-exitcodes
+  local exit_code=$?
+  if [[ $exit_code == 0 || $exit_code == 2 ]]; then
+    juju-log "The run succeeded. Exit code is $exit_code."
+  else
+    juju-log "The run failed. Exit code is $exit_code."
+    exit 1
+  fi
+  set -e
 }
 
 function cluster-cmd {
-	server-cmd "scaleio::login {'login': password=>$MY_PASSWORD} -> $1"
+  server-cmd "scaleio::login {'login': password=>$MY_PASSWORD} -> $1"
 }
 
 function relation-set-all {
-	rid=`relation-ids scaleio-sds`
-	if [ -z "$rid" ]; then return; fi
-	relation-set -r $rid protection-domain=$(config-get protection-domain)
-	relation-set -r $rid fault-set=$(config-get fault-set)
-	relation-set -r $rid storage-pools=$(config-get storage-pools)
-	relation-set -r $rid device_paths=$(config-get device-paths)
+  rid=`relation-ids scaleio-sds`
+  if [ -z "$rid" ]; then return; fi
+  relation-set -r $rid protection-domain=$(config-get protection-domain)
+  relation-set -r $rid fault-set=$(config-get fault-set)
+  relation-set -r $rid storage-pools=$(config-get storage-pools)
+  relation-set -r $rid device_paths=$(config-get device-paths)
 }
 
 function log-relation {
-	remote_name=${JUJU_REMOTE_UNIT/\//-} 
-	remote_ip=`relation-get private-address`
-	juju-log "$1: $remote_name, $remote_ip"
+  remote_name=${JUJU_REMOTE_UNIT/\//-} 
+  remote_ip=`relation-get private-address`
+  juju-log "$1: $remote_name, $remote_ip"
 }
