remove temporary apt-repo solution. implement downloading packages from ftp for puppet.

diff --git a/trusty/scaleio-gw/hooks/install b/trusty/scaleio-gw/hooks/install
--- a/trusty/scaleio-gw/hooks/install
+++ b/trusty/scaleio-gw/hooks/install
@@ -15,7 +15,12 @@ fi
 puppet module install --version "<1.2.0" cloudscaling-scaleio || /bin/true
 
 api_port=$(get-port)
-server-cmd "class { 'scaleio::gateway_server': port=>'$api_port' }"
+scaleio_packages_url=$(config-get scaleio-packages-url)
+if [[ -z "$scaleio_packages_url" ]] ; then
+  juju-log -l 'ERROR' "URL for packages absent. Can't install ScaleIO."
+  exit 1
+fi
+server-cmd "class { 'scaleio::gateway_server': port=>'$api_port', pkg_src=>'$scaleio_packages_url' }"
 
 juju-log "ScaleIO GW installed"
 
diff --git a/trusty/scaleio-mdm/hooks/install b/trusty/scaleio-mdm/hooks/install
--- a/trusty/scaleio-mdm/hooks/install
+++ b/trusty/scaleio-mdm/hooks/install
@@ -14,7 +14,12 @@ if ! puppet --version ; then
 fi
 puppet module install --version "<1.2.0" cloudscaling-scaleio || /bin/true
 
-server-cmd "class { 'scaleio::mdm_server': }"
+scaleio_packages_url=$(config-get scaleio-packages-url)
+if [[ -z "$scaleio_packages_url" ]] ; then
+  juju-log -l 'ERROR' "URL for packages absent. Can't install ScaleIO."
+  exit 1
+fi
+server-cmd "class { 'scaleio::mdm_server': pkg_src=>'$scaleio_packages_url' }"
 
 juju-log "ScaleIO MDM installed"
 
diff --git a/trusty/scaleio-sdc/hooks/install b/trusty/scaleio-sdc/hooks/install
--- a/trusty/scaleio-sdc/hooks/install
+++ b/trusty/scaleio-sdc/hooks/install
@@ -15,7 +15,12 @@ fi
 puppet module install --version "<1.2.0" cloudscaling-scaleio || /bin/true
 
 ftp=`config-get scaleio-driver-ftp`
-server-cmd "class { 'scaleio::sdc_server': ftp=>'$ftp' }"
+scaleio_packages_url=$(config-get scaleio-packages-url)
+if [[ -z "$scaleio_packages_url" ]] ; then
+  juju-log -l 'ERROR' "URL for packages absent. Can't install ScaleIO."
+  exit 1
+fi
+server-cmd "class { 'scaleio::sdc_server': ftp=>'$ftp', pkg_src=>'$scaleio_packages_url' }"
 
 status-set waiting "Awaiting relation to scaleio-mdm"
 
diff --git a/trusty/scaleio-sds/hooks/install b/trusty/scaleio-sds/hooks/install
--- a/trusty/scaleio-sds/hooks/install
+++ b/trusty/scaleio-sds/hooks/install
@@ -18,7 +18,12 @@ ftp=`config-get scaleio-driver-ftp`
 if [ -n "$ftp" ] ; then
   ftp_opt="ftp=>'$ftp'"
 fi
-server-cmd "class { 'scaleio::sds_server': $ftp_opt }"
+scaleio_packages_url=$(config-get scaleio-packages-url)
+if [[ -z "$scaleio_packages_url" ]] ; then
+  juju-log -l 'ERROR' "URL for packages absent. Can't install ScaleIO."
+  exit 1
+fi
+server-cmd "class { 'scaleio::sds_server': pkg_src=>'$scaleio_packages_url', $ftp_opt }"
 
 status-set waiting "Awaiting relation to scaleio-mdm"
 
